
fa=2; 

CtrlVar.MeshAdapt.GLrange=...
        [2*CtrlVar.MeshSize   CtrlVar.MeshSize/2/fa ; ...
        CtrlVar.MeshSize   CtrlVar.MeshSize/5/fa ; ...
        CtrlVar.MeshSize/2   CtrlVar.MeshSize/10/fa ];